---
# Variable file

username: haris

# Apt packages
apt_packages:
  - apt-transport-https
  - docker.io
  - codium
  - signal-desktop
  - gnome-tweaks
  - firefox
  - zsh
  - htop
  - terminator
  - btop
  - nvtop
  - bashtop
  - iftop
  - keepassxc
  - libreoffice
  - qbittorrent
  - steam
  - vlc
  - mpv
  - bleachbit
  - flameshot
  - kid3
  - mcomix
  - obs-studio
  - rhythmbox
  - thunderbird
  - variety
  - virtualbox
  - neofetch
  - kdenlive
  - akregator
  - cherrytree
  - clamav
  - lynis
  - chkrootkit
  - rkhunter
  - curl
  - snapd

apt_signed_repos:
  - 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable'
  - 'deb [signed-by=/etc/apt/trusted.gpg.d/vscodium-archive-keyring.asc] https://download.vscodium.com/debs vscodium main'
  - 'deb [signed-by=/etc/apt/trusted.gpg.d/signal-desktop-keyring.asc] https://updates.signal.org/desktop/apt xenial main'

# Install flatpak and listed packages
flatpak_packages:
  - name: com.github.z.Cumulonimbus 
  - name: org.gnome.DejaDup 
  - name: io.freetubeapp.FreeTube
  - name: net.lutris.Lutris
  - name: org.onlyoffice.desktopeditors
  - name: io.github.shiftey.Desktop
  - name: io.gitlab.librewolf-community
  - name: md.obsidian.Obsidian
  - name: com.zettlr.Zettlr
  - name: com.github.tchx84.Flatseal
  - name: net.cozic.joplin_desktop
  - name: com.vscodium.codium
  - name: org.kde.kdenlive
  - name: org.keepassxc.KeePassXC

# Install snap and and listed packages
snap_packages:
  - name: bitwarden

#currently missing apps
#ProtonVPN | VeraCrypt | brave | TOR | Lynis 
#Issues - bitwarden not installed properly