- name: Debian+Kicksecure Configuration
  hosts: all
  
  vars_files:
    - debian_config.yml

  roles:
    - role: petermosmans.customize-gnome
      tags: ["gnome"]
    
  tasks:
    - name: Install apt packages that have keys
      ansible.builtin.import_tasks:
        file: tasks/apt_signed.yml
      tags: ["apt_signed"]

    - name: Install apt packages
      ansible.builtin.import_tasks:
        file: tasks/apt.yml
      tags: ["apt"]

    - name: Install flatpak packages
      ansible.builtin.import_tasks:
        file: tasks/flatpak.yml
      tags: ["flatpak"]
    
    - name: "Install the tor browser in /home/{{ username }}/Downloads/"
      ansible.builtin.import_tasks:
        file: tasks/tor.yml
      tags: ["tor"]

    - name: Install .deb packages
      ansible.builtin.import_tasks:
        file: tasks/deb_packages.yml
      tags: ["deb"]
    
    - name: Install npm packages
      ansible.builtin.import_tasks:
        file: tasks/npm.yml
      tags: ["npm"]
    
    - name: Install Theme and Icons
      ansible.builtin.import_tasks:
        file: tasks/customization.yml
      tags: ["theme_icons"]

    - name: Tweaks
      ansible.builtin.import_tasks:
        file: tasks/tweaks.yml
      tags: ["tweaks"]

    - name: Install snap packages
      ansible.builtin.import_tasks:
        file: tasks/snap.yml
      tags: ["snap"]

    - name: Install Kicksecure
      ansible.builtin.import_tasks:
        file: tasks/kicksecure.yml
      tags: ["kicksecure"]