- name: Debian+Kicksecure Configuration
  hosts: all
  
  vars_files:
    - debian_config.yml

  roles:
    - role: petermosmans.customize-gnome
      tags: ["gnome"]
    
  tasks:
    - name: Install Apt packages that have keys
      ansible.builtin.import_tasks:
        file: tasks/apt_signed.yml
      tags: ["apt_signed"]

    - name: Install Apt packages
      ansible.builtin.import_tasks:
        file: tasks/apt.yml
      tags: ["apt"]

    - name: Install Flatpak packages
      ansible.builtin.import_tasks:
        file: tasks/flatpak.yml
      tags: ["flatpak"]

    - name: Install .deb packages
      ansible.builtin.import_tasks:
        file: tasks/deb_packages.yml
      tags: ["deb"]
    
    - name: Install npm packages
      ansible.builtin.import_tasks:
        file: tasks/npm.yml
      tags: ["npm"]
    
    - name: Install Theme, Font, Icons, and Browsers
      ansible.builtin.import_tasks:
        file: tasks/customization.yml
      tags: ["customization"]

    - name: Install Snap packages
      ansible.builtin.import_tasks:
        file: tasks/snap.yml
      tags: ["snap"]

    - name: Install Kicksecure
      ansible.builtin.import_tasks:
        file: tasks/kicksecure.yml
      tags: ["kicksecure"]