- name: Ubuntu Configuration
  hosts: all
  
  roles:
    - role: petermosmans.customize-gnome
      when: configure_gnome
      tags: ["gnome"]

  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world



