- name: Ubuntu Configuration
  hosts: all
  
  vars_files:
    - config.yml

  tasks:
    - name: Include apt packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/apt.yml
      tags: ["apt"]

    - name: Include flatpak packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/flatpak.yml
      tags: ["flatpak"]
      when: install_flatpak
      
    - name: Include snap packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/snap.yml
      tags: ["snap"]
      when: install_snap