---
#https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
#https://stackoverflow.com/questions/71585303/how-can-i-manage-keyring-files-in-trusted-gpg-d-with-ansible-playbook-since-apt

# Docker
- name: Add Docker apt repository key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  become: true

- name: Add Docker repository into sources list.
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable'
    state: present

# VSCodium
- name: Add VSCodium apt repository key.
  ansible.builtin.get_url:
    url: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
    dest: /etc/apt/trusted.gpg.d/vscodium-archive-keyring.asc
    mode: '0644'
    force: true
  become: true

- name: Add VSCodium repository into sources list.
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/vscodium-archive-keyring.asc] https://download.vscodium.com/debs vscodium main'
    state: present

# Brave - Error - repo is not signed
- name: Add Brave apt repository key.
  ansible.builtin.get_url:
    url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
    dest: /etc/apt/trusted.gpg.d/brave-browser-archive-keyring.asc
    mode: '0644'
    force: true
  become: true

- name: Add Brave repository into sources list.
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/brave-browser-archive-keyring.asc] https://brave-browser-apt-release.s3.brave.com/ stable main'
    state: present

# TOR - Error - repo is not signed
- name: Add TOR apt repository key.
  ansible.builtin.get_url:
    url: "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    dest: /etc/apt/trusted.gpg.d/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    mode: '0644'
    force: true
  become: true

- name: Add TOR repository into sources list.
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc] https://deb.torproject.org/torproject.org focal main'
    state: present

# Signal
- name: Add Signal apt repository key.
  ansible.builtin.get_url:
    url: "https://updates.signal.org/desktop/apt/keys.asc"
    dest: /etc/apt/trusted.gpg.d/signal-desktop-keyring.asc
    mode: '0644'
    force: true
  become: true

- name: Add Signal repository into sources list.
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/signal-desktop-keyring.asc] https://updates.signal.org/desktop/apt xenial main'
    state: present

# Adding all aforementioned repositories into sources list
- name: Add repositories into sources list.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ apt_signed_repos }}"
  when:
    - apt_signed_repos is defined
    - apt_signed_repos is iterable
    - apt_signed_repos | length > 0