---
# Docker
- name: Add Docker apt repository key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  become: true


# VSCodium
- name: Add VSCodium apt repository key.
  ansible.builtin.get_url:
    url: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
    dest: /etc/apt/trusted.gpg.d/vscodium-archive-keyring.asc
    mode: '0644'
    force: true
  become: true


# Brave - Error - repo is not signed
- name: Add Brave apt repository key.
  ansible.builtin.get_url:
    url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
    dest: /etc/apt/trusted.gpg.d/brave-browser-archive-keyring.asc
    mode: '0644'
    force: true
  become: true


# TOR - Error - repo is not signed
- name: Add TOR apt repository key.
  ansible.builtin.get_url:
    url: "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    dest: /etc/apt/trusted.gpg.d/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    mode: '0644'
    force: true
  become: true

# Signal
- name: Add Signal apt repository key.
  ansible.builtin.get_url:
    url: "https://updates.signal.org/desktop/apt/keys.asc"
    dest: /etc/apt/trusted.gpg.d/signal-desktop-keyring.asc
    mode: '0644'
    force: true
  become: true

# Adding all aforementioned repositories into sources list
- name: Add repositories into sources list.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  loop: "{{ apt_signed_repos }}"
  loop_control:
    pause: 5 # 5 seconds
  when:
    - apt_signed_repos is defined
    - apt_signed_repos is iterable
    - apt_signed_repos | length > 0