---
# Download and Install the cheat package

- name: Download Cheat
  become: true # since this uses sudo
  ansible.builtin.shell: |
    cd /tmp \
    && wget https://github.com/cheat/cheat/releases/download/4.4.0/cheat-linux-amd64.gz \
    && gunzip cheat-linux-amd64.gz \
    && chmod +x cheat-linux-amd64 \
    && sudo mv cheat-linux-amd64 /usr/local/bin/cheat

- name: Run `cheat` and answer the prompts to install cheat
  ansible.builtin.expect:
    command: cheat ls #using ls, but others could suffice as well
    responses: # you could copy the whole string here as well. This should use regex to match the questions 
      'create one now': 'Y'
      'community': 'Y'