---
#Install the cheat command and its community cheatsheets

- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: |
    cd /tmp \
    && wget https://github.com/cheat/cheat/releases/download/4.4.0/cheat-linux-amd64.gz \
    && gunzip cheat-linux-amd64.gz \
    && chmod +x cheat-linux-amd64 \
    && sudo mv cheat-linux-amd64 /usr/local/bin/cheat


- name: Clone the repo
  ansible.builtin.git:
    repo: 'https://github.com/cheat/cheatsheets.git'
    dest: "/home/{{ username }}/.config/cheat/cheatsheets/community"
    update: no

- name: Download the config file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/cheat/cheat/master/configs/conf.yml
    dest: "/home/{{ username }}/.config/cheat/conf.yml"

