---
# Install Flat Remix GNOME theme & Candy Icons

# Theme
- name: Create the theme directory (locally)
  ansible.builtin.file:
    path: "/home/{{ username }}/.themes"
    state: directory
    mode: '0755'

# NOTE: Theme only works for Terminal and not for Files app. Gnome seems to be applying the theme to certain apps.
# ## Dracula Theme
# - name: Download Dracula GTK Theme
#   ansible.builtin.unarchive:
#     src: 'https://github.com/dracula/gtk/releases/latest/download/Dracula.tar.xz'
#     dest: "/home/{{ username }}/.themes/"
#     remote_src: yes

# - name: Gsettings for theme (interface)
#   ansible.builtin.command: gsettings set org.gnome.desktop.interface gtk-theme "Dracula"

# - name: Gsettings for theme (WM Preference)
#   ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences theme "Dracula"

# Icon
- name: Create the icon directory (locally)
  ansible.builtin.file:
    path: "/home/{{ username }}/.icons"
    state: directory
    mode: '0755'

- name: Download Candy Icons
  ansible.builtin.unarchive:
    src: 'https://github.com/EliverLara/candy-icons/archive/refs/heads/master.zip'
    dest: "/home/{{ username }}/.icons/"
    remote_src: yes

- name: Gsettings for icons
  ansible.builtin.command: gsettings set org.gnome.desktop.interface icon-theme candy-icons-master

# Font
- name: Create .fonts Directory 
  file:
    path: "/home/{{ username }}/.fonts"
    state: directory

- name: Download FiraCode Nerd Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
    dest: "/home/{{ username }}/.fonts/"
    remote_src: yes

- name: Fonts Cache Reload
  ansible.builtin.shell: fc-cache -f

- name: Download tor
  ansible.builtin.get_url:
    url: "{{ tor_download_link }}"
    dest: "/home/{{ username }}/Downloads/"

- name: Unarchive the tor zip
  ansible.builtin.unarchive:
    src: "/home/{{ username }}/Downloads/{{ tor_file_ver }}"
    dest: "/home/{{ username }}/Downloads/"
    remote_src: yes

- name: Remove TOR archive
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/{{ tor_file_ver }}"
    state: absent

- name: Download Mullvad Browser
  ansible.builtin.get_url:
    url: https://mullvad.net/en/download/browser/linux-x86_64/latest
    dest: "/home/{{ username }}/Downloads/"

- name: Unarchive Mullvad Browser
  ansible.builtin.unarchive:
    src: "/home/{{ username }}/Downloads/{{ mullvad_browser_ver }}"
    dest: "/home/{{ username }}/Downloads/"
    remote_src: yes

- name: Add Mullvad Browser to App list
  ansible.builtin.copy:
    src: "/home/{{ username }}/Downloads/mullvad-browser/start-mullvad-browser.desktop"
    dest: "/home/{{ username }}/.local/share/applications/"

- name: Remove Mullvad archive
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/{{ mullvad_browser_ver }}"
    state: absent