---
#Downloading and Installing .deb packages
# Create a folder in Downloads for all .deb packages
- name: Create a directory for debian packages
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/debian"
    state: directory
    mode: '0755'
# VeraCrypt
- name: Download VeraCrypt .deb package
  ansible.builtin.get_url:
    url: "https://github.com/veracrypt/VeraCrypt/releases/latest/download/{{ veracrypt_file_ver }}"
    dest: "/home/{{ username }}/Downloads/debian/veracrypt-amd64.deb"

- name: Install VeraCrypt .deb package
  apt:
    deb: "/home/{{ username }}/Downloads/debian/veracrypt-amd64.deb"
  become: yes

# Fastfetch
- name: Download Fastfetch .deb package
  ansible.builtin.get_url:
    url: "https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb"
    dest: "/home/{{ username }}/Downloads/debian/fastfetch-linux-amd64.deb"

- name: Install VeraCrypt .deb package
  apt:
    deb: "/home/{{ username }}/Downloads/debian/fastfetch-linux-amd64.deb"
  become: yes

# FreeFileSync
- name: Create a directory for FreeFileSync
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/FreeFileSync"
    state: directory
    mode: '0755'

- name: Download FreeFileSync .deb package
  ansible.builtin.get_url:
    url: "https://freefilesync.org/download/{{ freefilesync_file_ver }}"
    dest: "/home/{{ username }}/Downloads/FreeFileSync/{{ freefilesync_file_ver }}"

- name: Extract FreeFileSync Installer into /Downloads/FreeFileSync
  ansible.builtin.unarchive:
    src: "/home/{{ username }}/Downloads/FreeFileSync/{{ freefilesync_file_ver }}"
    dest: /Downloads/FreeFileSync/FreeFileSync_Linux


- name: Removing debian directory (clean-up)
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/debian"
    state: absent