---
# Setup OhMyZsh with Powerlevel10k theme

- name: OhMyZsh Install (curl)
  ansible.builtin.expect:
    command: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
    responses:
      Question:
        - y # Change default shell to zsh
  become: true #you need to enter your sudo password, this should mitigate that

- name: Install Powerlevel10k
  ansible.builtin.shell: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"

#- name: Set ZSH Theme to Powerlevel10k
#  ansible.builtin.shell: "sed -i \"s/ZSH_THEME=\"robbyrussell\"/ZSH_THEME=\"powerlevel10k\/powerlevel10k\"/g\" ~/.zshrc"

- name: Set ZSH Theme to Powerlevel10k
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.zshrc"
    regexp: '^ZSH_THEME=\"robbyrussell\"'
    line: 'ZSH_THEME=\"powerlevel10k/powerlevel10k\"'

- name: zsh-syntax-highlighting install 
  ansible.builtin.shell: "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"

- name: zsh-autosuggestions install 
  ansible.builtin.shell: "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

- name: Add plugins
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.zshrc"
    regexp: '^plugins=(git)'
    line: 'plugins=( git zsh-syntax-highlighting zsh-autosuggestions )'