---
# Post Installation Reminders

- name: p10k
  ansible.builtin.debug:
    msg: Run `p10k configure` to configure ohmyzsh

- name: AppArmor for everything
  ansible.builtin.debug:
    msg: Install "https://github.com/Kicksecure/apparmor-profile-everything" to harden the system

