---
- name: Ensure Snapd installed
  become: true
  ansible.builtin.apt:
    name: snapd
    state: latest

- name: Install Snap packages
  become: true
  community.general.snap:
    name: "{{ item.name | default(item) }}"
    classic: "{{ item.classic | default(true) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ snap_packages }}"
  when: snap_packages is defined

# Link your snap .desktop folder inside one of your user or system .desktop folders
- name: Show snaps in Application list
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications
    dest: /home/{{ username }}/.local/share/applications/snap
    state: link
    become: true