---
# Install Flat Remix GNOME theme & Candy Icons

# Theme
- name: Create a directory for theme
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/theme"
    state: directory
    mode: '0755'

- name: Clone the repo
  ansible.builtin.git:
    repo: 'https://github.com/daniruiz/flat-remix-gnome.git'
    dest: "/home/{{ username }}/Downloads/theme"
    update: no

- name: Create the theme directory (locally)
  ansible.builtin.file:
    path: "/home/{{ username }}/.themes"
    state: directory
    mode: '0755'

- name: Copying themes (locally)
  ansible.builtin.synchronize:
    src: "/home/{{ username }}/Downloads/theme/themes/"
    dest: "/home/{{ username }}/.themes"

- name: Gsettings for theme
  ansible.builtin.command: gsettings set org.gnome.desktop.interface gtk-theme "Flat-Remix-GTK-Blue"

# Icon
- name: Create a directory for icons
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/icon"
    state: directory
    mode: '0755'

- name: Download icons .zip
  ansible.builtin.get_url:
    url: "https://github.com/EliverLara/candy-icons/archive/refs/heads/master.zip"
    dest: "/home/{{ username }}/Downloads/icon/candy_icons.zip"

- name: Create the icon directory (locally)
  ansible.builtin.file:
    path: "/home/{{ username }}/.icons"
    state: directory
    mode: '0755'

- name: Extract zip to .icons
  ansible.builtin.unarchive:
    src: "/home/{{ username }}/Downloads/icon/candy_icons.zip"
    dest: "/home/{{ username }}/.icons"

- name: Gsettings for icons
  ansible.builtin.command: gsettings set org.gnome.desktop.interface icon-theme candy-icons-master

# Clean-up for both
- name: Removing theme directory (clean-up)
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/theme"
    state: absent

- name: Removing icons directory (clean-up)
  ansible.builtin.file:
    path: "/home/{{ username }}/Downloads/icon"
    state: absent