---
- name: Download tor
  ansible.builtin.get_url:
    url: https://www.torproject.org/dist/torbrowser/12.0.7/tor-browser-linux64-12.0.7_ALL.tar.xz
    dest: "/home/{{ username }}/Downloads/"

- name: Unarchive the tor zip
  ansible.builtin.unarchive:
    src: "/home/{{ username }}/Downloads/tor-browser-linux64-12.0.7_ALL.tar.xz"
    dest: "/home/{{ username }}/Downloads/"
    remote_src: yes